export const books = {
    "AAG": "Astral Adventurer's Guide",
    "AATM": "Adventure Atlas: The Mortuary",
    "AI": "Acquisitions Incorporated",
    "AITFR-AVT": "Adventures in the Forgotten Realms: A Verdant Tomb",
    "AITFR-DN": "Adventures in the Forgotten Realms: Deepest Night",
    "AITFR-FCD": "Adventures in the Forgotten Realms: From Cyan Depths",
    "AITFR-ISF": "Adventures in the Forgotten Realms: In Scarlet Flames",
    "AITFR-THP": "Adventures in the Forgotten Realms: The Hidden Page",
    "AL": "Adventurers League",
    "AZFYT": "A Zib for Your Thoughts",
    "AWM": "Adventure With Muk",
    "BAM": "Boo's Astral Menagerie",
    "BGDIA": "Baldur's Gate: Descent Into Avernus",
    "BGG": "Bigby Presents: Glory of the Giants",
    "BMT": "The Book of Many Things",
    "BQGT": "Borderlands Quest: Goblin Trouble",
    "CM": "Candlekeep Mysteries",
    "COA": "Chains of Asmodeus",
    "COS": "Curse of Strahd",
    "CRCOTN": "Critical Role: Call of the Netherdeep",
    "DC": "Essentials Kit: Divine Contention",
    "DD": "Wildemount: Dangerous Designs",
    "DIP": "Essentials Kit: Dragon of Icespire Peak",
    "DITLCOT": "Descent into the Lost Caverns of Tsojcanth",
    "DMG": "Dungeon Master's Guide (2014)",
    "DMTCRG": "The Deck of Many Things: Card Reference Guide",
    "DOD": "Domains of Delight",
    "DOSI": "Dragons of Stormwreck Isle",
    "DRDE-ACFAS": "Dragon Delves: A Copper for a Song",
    "DRDE-BD": "Dragon Delves: Baker's Doesn't",
    "DRDE-BTS": "Dragon Delves: Before the Storm",
    "DRDE-DAS": "Dragon Delves: Death at Sunset",
    "DRDE-DOTSC": "Dragon Delves: Dragons of the Sandstone City",
    "DRDE-FWTVC": "Dragon Delves: For Whom the Void Calls",
    "DRDE-SD": "Dragon Delves: Shivering Death",
    "DRDE-TDON": "Dragon Delves: The Dragon of Najkir",
    "DRDE-TFV": "Dragon Delves: The Forbidden Vale",
    "DRDE-TWOO": "Dragon Delves: The Will of Orcus",
    "DSOTDQ": "Dragonlance: Shadow of the Dragon Queen",
    "EFR": "Eberron: Forgotten Relics",
    "EGW": "Explorer's Guide to Wildemount",
    "ERLW": "Eberron: Rising from the Last War",
    "ESK": "Essentials Kit",
    "FS": "Wildemount: Frozen Sick",
    "FTD": "Fizban's Treasury of Dragons",
    "GGR": "Guildmasters' Guide to Ravnica",
    "GOS": "Ghosts of Saltmarsh",
    "GOTSF": "Giants of the Star Forge",
    "HAT-TG": "Thieves' Gallery",
    "HBTD": "Hold Back The Dead",
    "HF": "Heroes' Feast",
    "HFFOTM": "Heroes' Feast Flavors of the Multiverse",
    "HFSTCM": "Heroes' Feast: Saving the Children's Menu",
    "HFTT": "Hunt for the Thessalhydra",
    "HOL": "Ravenloft: The House of Lament",
    "HOTDQ": "Hoard of the Dragon Queen",
    "IDROTF": "Icewind Dale: Rime of the Frostmaiden",
    "IMR": "Infernal Machine Rebuild",
    "JTTRC": "Journeys through the Radiant Citadel",
    "KFTGV": "Keys from the Golden Vault",
    "KKW": "Krenko's Way",
    "LK": "Lightning Keep",
    "LLK": "Lost Laboratory of Kwalish",
    "LMOP": "Lost Mine of Phandelver",
    "LOX": "Light of Xaryxis",
    "LR": "Locathah Rising",
    "LRDT": "Red Dragon's Tale: A LEGO Adventure",
    "MABJOV": "Minsc and Boo's Journal of Villainy",
    "MCV1SC": "Monstrous Compendium Volume 1: Spelljammer Creatures",
    "MCV2DC": "Monstrous Compendium Volume 2: Dragonlance Creatures",
    "MCV3MC": "Monstrous Compendium Volume 3: Minecraft Creatures",
    "MCV4EC": "Monstrous Compendium Volume 4: Eldraine Creatures",
    "MISMV1": "Misplaced Monsters: Volume 1", 
    "MM": "Monster Manual (2014)",
    "MOT": "Mythic Odysseys of Theros",
    "T-NSS": "Theros: No Silent Secret",
    "MFF": "Mordenkainen's Fiendish Folio",
    "MGELFT": "Muk's Guide To Everything He Learned From Tasha",
    "MPMM": "Mordenkainen Presents: Monsters of the Multiverse",
    "MPP": "Morte's Planar Parade",
    "MTF": "Mordenkainen's Tome of Foes",
    "NRH-ASS": "NERDS Restoring Harmony: A Sticky Situation",
    "NRH-AT": "NERDS Restoring Harmony: Adventure Together",
    "NRH-AVITW": "NERDS Restoring Harmony: A Voice in the Wilderness",
    "NRH-AWOL": "NERDS Restoring Harmony: A Web of Lies",
    "NRH-COI": "NERDS Restoring Harmony: Circus of Illusion",
    "NRH-TCMC": "NERDS Restoring Harmony: The Candy Mountain Caper",
    "NRH-TLT": "NERDS Restoring Harmony: The Lost Tomb",
    "OGA": "One Grung Above",
    "OOTA": "Out of the Abyss",
    "OOW": "The Orrery of the Wanderer",
    "PABTSO": "Phandelver and Below: The Shattered Obelisk",
    "PAF": "Puncheons and Flagons",
    "PHB": "Player's Handbook (2014)",
    "PIP": "Peril in Pinebrook",
    "POTA": "Princes of the Apocalypse",
    "PSA": "Plane Shift: Amonkhet",
    "PSD": "Plane Shift: Dominaria",
    "PSI": "Plane Shift: Innistrad",
    "PSK": "Plane Shift: Kaladesh",
    "PSX": "Plane Shift: Ixalan",
    "PSZ": "Plane Shift: Zendikar",
    "QFTIS": "Quests from the Infinite Staircase",
    "RMBRE": "The Lost Dungeon of Rickedness: Big Rick Energy",
    "RMR": "Dungeons & Dragons vs. Rick and Morty: Basic Rules",
    "ROT": "Rise of Tiamat",
    "RTG": "Return to the Glory",
    "SAC": "Sage Advice Compendium",
    "SADS": "Sapphire Anniversary Dice Set",
    "SATO": "Sigil and the Outlands",
    "SCAG": "Sword Coast Adventurer's Guide",
    "SCC-ARIR": "Strixhaven: A Reckoning in Ruins",
    "SCC-CK": "Strixhaven: Campus Kerfuffle",
    "SCC-HFMT": "Strixhaven: Hunt for Mage Tower",
    "SCC-TMM": "Strixhaven: The Magister's Masquerade",
    "SCC": "Strixhaven: A Curriculum of Chaos",
    "SCOEE": "Scions of Elemental Evil",
    "SCREEN": "Dungeon Master's Screen",
    "SCREENDUNGEONKIT": "Dungeon Master's Screen: Dungeon Kit",
    "SCREENSPELLJAMMER": "Dungeon Master's Screen: Spelljammer",
    "SCREENWILDERNESSKIT": "Dungeon Master's Screen: Wilderness Kit",
    "SDW": "Essentials Kit: Sleeping Dragon's Wake",
    "SJA": "Spelljammer Academy",
    "SKT": "Storm King's Thunder",
    "SLW": "Essentials Kit: Storm Lord's Wrath",
    "TCE": "Tasha's Cauldron of Everything",
    "TD": "Tarot Deck",
    "TDCSR": "Tal'Dorei Campaign Setting Reborn",
    "TFTYP": "Tales from the Yawning Portal",
    "TFTYP-ATG": "Tales from the Yawning Portal: Against the Giants",
    "TFTYP-DIT": "Tales from the Yawning Portal: Dead in Thay",
    "TFTYP-TFOF": "Tales from the Yawning Portal: The Forge of Fury",
    "TFTYP-THSOT": "Tales from the Yawning Portal: The Hidden Shrine of Tamoachan",
    "TFTYP-TOH": "Tales from the Yawning Portal: Tomb of Horrors",
    "TFTYP-TSC": "Tales from the Yawning Portal: The Sunless Citadel",
    "TFTYP-WPM": "Tales from the Yawning Portal: White Plume Mountain",
    "TLK": "The Lost Kenku",
    "TOA": "Tomb of Annihilation",
    "TOFW": "Turn of Fortune's Wheel",
    "TOR": "Wildemount: Tide of Retribution",
    "TTP": "The Tortle Package",
    "US": "Wildemount: Unwelcome Spirits",
    "UTHFTLH": "Uni and the Hunt for the Lost Horn",
    "VD": "Vecna Dossier",
    "VEOR": "Vecna: Eve of Ruin",
    "VGM": "Volo's Guide to Monsters",
    "VNOTEE": "Vecna: Nest of the Eldritch Eye",
    "VRGR": "Van Richten's Guide to Ravenloft",
    "WBTW": "The Wild Beyond the Witchlight",
    "WDH": "Waterdeep: Dragon Heist",
    "WDMM": "Waterdeep: Dungeon of the Mad Mage",
    "XDMG": "Dungeon Master's Guide (2024)",
    "XGE": "Xanathar's Guide to Everything",
    "XMM": "Monster Manual (2025)",
    "XMTS": "X Marks the Spot",
    "XPHB": "Player's Handbook (2024)",
    "XSCREEN": "Dungeon Master's Screen (2024)",
};
