// Monster tags.
export const tags = [
    // Just keep the text in italic, if | is found, stop there.
    '{@action Attack}',
    '{@action cast a spell|PHB|casts an innate spell}',
    '{@action Dash}',
    '{@action Disengage}',
    '{@action Dodge}',
    '{@action grapple}',
    '{@action Help}',
    '{@action Hide}',
    '{@action opportunity attack}',
    '{@action opportunity attack||opportunity attacks}',
    '{@action opportunity attack|PHB}',
    '{@action opportunity attack|PHB|opportunity attacks}',
    '{@action Opportunity Attack|XPHB|Opportunity Attacks}',
    '{@action Search}',

    // Do nothing
    '{@actResponse d}',
    '{@actResponse}',

    // Replace for the comment on each one.
    '{@actSave cha}', // Charisma
    '{@actSave con}', // Constitution
    '{@actSave dex}', // Dexterity
    '{@actSave int}', // Intelligence
    '{@actSave str}', // Strength
    '{@actSave wis}', // Wisdom

    // Replace for the comment on each one.
    '{@actSaveFail}', // Failed
    '{@actSaveFail 1}', // Failed by 1
    '{@actSaveFail 2}', // Failed by 2
    '{@actSaveFailBy 5}', // Failed by 5
    '{@actSaveSuccess}', // Success
    '{@actSaveSuccessOrFail}', // Success or Fail
    '{@actTrigger}', // Trigger

    // Just keep the text in italic, if | is found, stop there.
    '{@adventure area 31|WDMM|15|31. Hall of Embers}',
    '{@adventure Faerzress|OotA|1|Faerzress}',
    '{@adventure Hoard of the Dragon Queen|HotDQ}',
    '{@adventure Rise of Tiamat|RoT}',
    '{@adventure Shrine of Umberlee|ttp|3|24. Shrine of Umberlee}',
    '{@adventure society member|OotA|1|Society of Brilliance}',
    '{@adventure The Rise of Tiamat|RoT}',

    // Replace for the comment on each one.
    '{@atk m}', // Melee attack
    '{@atk ms,rs}', // Melee Spell Attack, Ranged Spell Attack
    '{@atk ms}', // Melee Spell Attack
    '{@atk mw,rw}', // Melee Weapon Attack, Ranged Weapon Attack
    '{@atk mw}', // Melee Weapon Attack
    '{@atk rs}', // Ranged Spell Attack
    '{@atk rw}', // Ranged Weapon Attack
    '{@atkr m,r}', // Melee Attack, Ranged Attack
    '{@atkr m}', // Melee Attack
    '{@atkr r}', // Ranged Attack

    // Just keep the text in italic, if | is found, stop there.
    '{@b severed arm}',
    '{@b severed head}',
    '{@b severed leg}',

    // Just keep the text in italic, if | is found, stop there.
    '{@book chapter 7|DMG|7|Other Rewards}',
    '{@book Dungeon Master\'s Guide|dmg|8|madness}',
    '{@book League of Miracles|TDCSR|2|League of Miracles}',
    '{@book Monster Manual|MM}',
    '{@book Player\'s Handbook|PHB}',
    '{@book Volo\'s Guide to Monsters|VGM}',

    // Replace for the comment on each one.
    '{@chance 25}', // 25% chance
    '{@chance 25|25 percent|25% summoning chance}', // 25% summoning chance
    '{@chance 30}', // 30% chance
    '{@chance 30|30 percent|30% summoning chance}', // 30% summoning chance
    '{@chance 40}', // 40% chance
    '{@chance 40|40 percent|40% summoning chance}', // 40% summoning chance
    '{@chance 50}', // 50% chance
    '{@chance 50|50 percent|50% summoning chance}', // 50% summoning chance
    '{@chance 60}', // 60% chance

    // Just keep the text in italic, if | is found, add next text between parenthesis.
    '{@condition blinded}',
    '{@condition Blinded|XPHB}',
    '{@condition charmed}',
    '{@condition Charmed|XPHB}',
    '{@condition deafened}',
    '{@condition Deafened|XPHB}',
    '{@condition exhaustion}',
    '{@condition Exhaustion|XPHB}',
    '{@condition frightened}',
    '{@condition Frightened|XPHB}',
    '{@condition grappled}',
    '{@condition Grappled|XPHB}',
    '{@condition incapacitated}',
    '{@condition Incapacitated|XPHB}',
    '{@condition invisible}',
    '{@condition Invisible|XPHB}',
    '{@condition paralyzed}',
    '{@condition Paralyzed|XPHB}',
    '{@condition petrified}',
    '{@condition Petrified|XPHB}',
    '{@condition poisoned}',
    '{@condition Poisoned|XPHB}',
    '{@condition prone}',
    '{@condition Prone|XPHB}',
    '{@condition restrained}',
    '{@condition Restrained|XPHB}',
    '{@condition stunned}',
    '{@condition Stunned|XPHB}',
    '{@condition unconscious}',
    '{@condition Unconscious|XPHB}',

    // Add a link to open the creature in the bestiary.
    '{@creature abyssal wretch|mtf}',
    '{@creature adult black dragon}',
    '{@creature adult bronze dragon}',
    '{@creature air elemental}',
    '{@creature air elemental||air elementals}',
    '{@creature ancient gold dragon||ancient gold dragons}',
    '{@creature art elemental mascot|SCC|elemental mascots}',
    '{@creature Auril (second form)|IDRotF|second form}',
    '{@creature Auril (third form)|IDRotF|third form}',
    '{@creature babau|MPMM|babaus}',
    '{@creature barbed devil}',
    '{@creature barbed devil||barbed devils}',
    '{@creature barlgura||barlguras}',
    '{@creature bat|mm|bats}',
    '{@creature bearded devil||bearded devils}',
    '{@creature Bhaal, Ravager|MaBJoV|ravager form}',
    '{@creature Bhaal, Slayer|MaBJoV|slayer form}',
    '{@creature bone devil}',
    '{@creature chasme||chasmes}',
    '{@creature Chishinix\' Head|PaBTSO|severed head}',
    '{@creature crawling claw}',
    '{@creature crocodile}',
    '{@creature death slaad||death slaadi}',
    '{@creature death\'s head|VRGR}',
    '{@creature death\'s head|VRGR|death\'s heads}',
    '{@creature demilich}',
    '{@creature Doty X|TDCSR|Doty}',
    '{@creature dragonsoul|RoT}',
    '{@creature dretch||dretches}',
    '{@creature drow elite warrior}',
    '{@creature drow priestess of Lolth}',
    '{@creature drow}',
    '{@creature eagle}',
    '{@creature earth elemental}',
    '{@creature Earth Elemental}',
    '{@creature earth elemental||earth elementals}',
    '{@creature eidolon|MPMM}',
    '{@creature eidolon|MTF}',
    '{@creature Elder Dinosaur (Etali, Primal Storm)|PSX|Etali, Primal Storm}',
    '{@creature Elder Dinosaur (Ghalta, Primal Hunger)|PSX|Ghalta, Primal Hunger}',
    '{@creature Elder Dinosaur (Nezahal, Primal Tide)|PSX|Nezahal, Primal Tide}',
    '{@creature Elder Dinosaur (Tetzimoc, Primal Death)|PSX|Tetzimoc, Primal Death}',
    '{@creature Elder Dinosaur (Zacama, Primal Calamity)|PSX|Zacama, Primal Calamity}',
    '{@creature Elder Dinosaur (Zetalpa, Primal Dawn)|PSX|Zetalpa, Primal Dawn}',
    '{@creature elk}',
    '{@creature encephalon gemmule|PaBTSO}',
    '{@creature erinyes}',
    '{@creature farastu stalker|MaBJoV|farastu stalkers}',
    '{@creature fire elemental}',
    '{@creature fire elemental||fire elementals}',
    '{@creature flameskull}',
    '{@creature flesh golem|MM|flesh golems}',
    '{@creature fractal mascot|SCC|fractal mascots}',
    '{@creature frost giant}',
    '{@creature galeb duhr}',
    '{@creature gargoyle}',
    '{@creature ghast}',
    '{@creature ghoul}',
    '{@creature giant bat|mm|giant bats}',
    '{@creature giant centipede||giant centipedes}',
    '{@creature giant octopus}',
    '{@creature giant rat|mm|giant rats}',
    '{@creature giant spider}',
    '{@creature giant spider|mm|giant spiders}',
    '{@creature gibbering mouther}',
    '{@creature glabrezu}',
    '{@creature glabrezu||glabrezus}',
    '{@creature gnoll fang of Yeenoghu}',
    '{@creature gnoll||gnolls}',
    '{@creature Goat-Knight Steed|TDCSR}',
    '{@creature goblin||goblins}',
    '{@creature goristro}',
    '{@creature green slaad}',
    '{@creature Green Slaad|XMM}',
    '{@creature hell hound||hell hounds}',
    '{@creature hezrou||hezrous}',
    '{@creature horned devil}',
    '{@creature hunter shark}',
    '{@creature husk zombie|EGW}',
    '{@creature ice devil}',
    '{@creature ice mephit}',
    '{@creature imp}',
    '{@creature Incubus|XMM}',
    '{@creature indentured spirit|ggr|indentured spirits}',
    '{@creature inkling mascot|SCC|inkling mascots}',
    '{@creature kelubar consul|MaBJoV}',
    '{@creature Kraghammer Goat-Knight|TDCSR|goat-knight}',
    '{@creature lemure}',
    '{@creature mage}',
    '{@creature mammoth}',
    '{@creature manes}',
    '{@creature marilith}',
    '{@creature marilith||mariliths}',
    '{@creature martial arts adept|vgm}',
    '{@creature mezzoloth||mezzoloths}',
    '{@creature mind flayer}',
    '{@creature mind flayer||mind flayers}',
    '{@creature minotaur||minotaurs}',
    '{@creature Myconid Spore Servant|XMM}',
    '{@creature nalfeshnee||nalfeshnees}',
    '{@creature Needle Blight|XMM}',
    '{@creature nightmare}',
    '{@creature nycaloth||nycaloths}',
    '{@creature otyugh}',
    '{@creature owl}',
    '{@creature pest mascot|SCC|pest mascots}',
    '{@creature pit fiend}',
    '{@creature planetar}',
    '{@creature priest}',
    '{@creature pseudodragon}',
    '{@creature quaggoth spore servant||spore servant}',
    '{@creature quasit}',
    '{@creature rat}',
    '{@creature rat|mm|rats}',
    '{@creature red slaad}',
    '{@creature Red Slaad|XMM}',
    '{@creature retriever|mtf}',
    '{@creature sacred statue|MPMM}',
    '{@creature sacred statue|MPMM|sacred statue\'s stat block}',
    '{@creature sacred statue|mtf}',
    '{@creature scion of Grolantor|BGG}',
    '{@creature scion of Memnor|BGG}',
    '{@creature scion of Skoraeus|BGG}',
    '{@creature scion of Stronmaus|BGG}',
    '{@creature scion of Surtur|BGG}',
    '{@creature scion of Thrym|BGG}',
    '{@creature scorpion}',
    '{@creature shadow demon}',
    '{@creature shadow}',
    '{@creature shadow||shadows}',
    '{@creature Shadow|XMM}',
    '{@creature shator warden|MaBJoV}',
    '{@creature shield guardian}',
    '{@creature skeleton||skeletons}',
    '{@creature slaad tadpole}',
    '{@creature specter}',
    '{@creature specter||specters}',
    '{@creature Specter|XMM}',
    '{@creature spined devil}',
    '{@creature spined devil||spined devils}',
    '{@creature spirit statue mascot|SCC|statue mascots}',
    '{@creature Steel Defender|TCE|metallic panther}',
    '{@creature stirge}',
    '{@creature stirge||stirges}',
    '{@creature storm giant}',
    '{@creature Succubus|XMM}',
    '{@creature swarm of bats||bats}',
    '{@creature swarm of bats||swarms of bats}',
    '{@creature swarm of centipedes||swarm of insects (centipedes)}',
    '{@creature Swarm of Centipedes||swarm of insects (centipedes)}',
    '{@creature swarm of insects}',
    '{@creature swarm of poisonous snakes}',
    '{@creature swarm of rats||rats}',
    '{@creature swarm of rats||swarms of rats}',
    '{@creature swarm of rot grubs|MPMM}',
    '{@creature swarm of rot grubs|vgm}',
    '{@creature swarm of spiders||swarms of spiders}',
    '{@creature swarm of wasps||swarm of insects (wasps)}',
    '{@creature Swarm of Wasps||swarm of insects (wasps)}',
    '{@creature sword wraith warrior|MPMM|sword wraith warriors}',
    '{@creature sword wraith warrior|mtf|sword wraith warriors}',
    '{@creature Taryon Darrington|TDCSR|Tary}',
    '{@creature Thessalar\'s homunculus|IMR}',
    '{@creature treant}',
    '{@creature Trinket|TDCSR}',
    '{@creature Troll Limb|XMM}',
    '{@creature Troll|XMM}',
    '{@creature Twig Blight|XMM}',
    '{@creature vampire spawn}',
    '{@creature Vampire Spawn|XMM}',
    '{@creature vampire}',
    '{@creature Vex\'ahlia|TDCSR|Vex\'s}',
    '{@creature Vine Blight|XMM}',
    '{@creature vrock||vrocks}',
    '{@creature war priest|vgm}',
    '{@creature water elemental}',
    '{@creature water elemental||water elementals}',
    '{@creature water weird||water weirds}',
    '{@creature wight}',
    '{@creature winter wolf}',
    '{@creature wolf}',
    '{@creature wolf||wolves}',
    '{@creature wraith}',
    '{@creature xorn}',
    '{@creature yeti||yetis}',
    '{@creature yochlol}',
    '{@creature young bronze dragon}',
    '{@creature young solar dragon|BAM}',
    '{@creature young white dragon||young white dragons}',
    '{@creature zombie}',
    '{@creature zombie||zombies}',
    '{@creature Zombie|XMM}',
    '{@creature Zuggtmoy|MTF}',

    // Add the value between parenthesis after last |.
    '{@damage (#$prompt_number:min=1,title=Enter the creature\'s CR!,default=1$#)d8|A number of  d8s of necrotic damage equal to the creature\'s challenge rating}',
    '{@damage (PB)d6|A number of d6s of necrotic damage equal to your proficiency bonus}',

    // Add the value between parenthesis.
    '{@damage (summonSpellLevel - 3)d12 + 3|2d12 + 3}',
    '{@damage (summonSpellLevel - 3)d6 + 3|2d6 + 3}',
    '{@damage (summonSpellLevel - 4)d4 + 3|1d4 + 3}',
    '{@damage + 1d6}',
    '{@damage 10d10}',
    '{@damage 10d12 + 5}',
    '{@damage 10d12}',
    '{@damage 10d4}',
    '{@damage 10d6 + 40}',
    '{@damage 10d6 + 9}',
    '{@damage 10d6}',
    '{@damage 10d8 + 5}',
    '{@damage 10d8 + 6}',
    '{@damage 10d8}',
    '{@damage 11d10}',
    '{@damage 11d12}',
    '{@damage 11d6}',
    '{@damage 11d8}',
    '{@damage 12d10 + 7}',
    '{@damage 12d10}',
    '{@damage 12d12}',
    '{@damage 12d6}',
    '{@damage 12d8}',
    '{@damage 13d10}',
    '{@damage 13d12}',
    '{@damage 13d6}',
    '{@damage 13d8}',
    '{@damage 14d10}',
    '{@damage 14d6 + 40}',
    '{@damage 14d6}',
    '{@damage 14d8}',
    '{@damage 15d10}',
    '{@damage 15d6}',
    '{@damage 15d8}',
    '{@damage 16d10}',
    '{@damage 16d4}',
    '{@damage 16d6}',
    '{@damage 16d8}',
    '{@damage 17d6}',
    '{@damage 18d6}',
    '{@damage 1d10 + 1}',
    '{@damage 1d10 + 10}',
    '{@damage 1d10 + 12}',
    '{@damage 1d10 + 2}',
    '{@damage 1d10 + 3 + summonSpellLevel}',
    '{@damage 1d10 + 3}',
    '{@damage 1d10 + 4 + summonSpellLevel}',
    '{@damage 1d10 + 4}',
    '{@damage 1d10 + 5}',
    '{@damage 1d10 + 6}',
    '{@damage 1d10 + 7}',
    '{@damage 1d10 + 8}',
    '{@damage 1d10 + 9}',
    '{@damage 1d10 + PB}',
    '{@damage 1d10}',
    '{@damage 1d12 + 1}',
    '{@damage 1d12 + 10}',
    '{@damage 1d12 + 14}',
    '{@damage 1d12 + 2}',
    '{@damage 1d12 + 3 + summonSpellLevel}',
    '{@damage 1d12 + 3}',
    '{@damage 1d12 + 4}',
    '{@damage 1d12 + 5}',
    '{@damage 1d12 + 6}',
    '{@damage 1d12 + 7}',
    '{@damage 1d12 + 8}',
    '{@damage 1d12 + 9}',
    '{@damage 1d12}',
    '{@damage 1d3 + 2}',
    '{@damage 1d3}',
    '{@damage 1d4 - 1}',
    '{@damage 1d4 - 3}',
    '{@damage 1d4 + 1}',
    '{@damage 1d4 + 12}',
    '{@damage 1d4 + 2}',
    '{@damage 1d4 + 3 + PB}',
    '{@damage 1d4 + 3}',
    '{@damage 1d4 + 4}',
    '{@damage 1d4 + 5}',
    '{@damage 1d4 + 6}',
    '{@damage 1d4 + 7}',
    '{@damage 1d4 + 8}',
    '{@damage 1d4 + PB}',
    '{@damage 1d4}',
    '{@damage 1d4+2}',
    '{@damage 1d6 - 1}',
    '{@damage 1d6 - 2}',
    '{@damage 1d6 + 0}',
    '{@damage 1d6 + 1}',
    '{@damage 1d6 + 10}',
    '{@damage 1d6 + 2 + PB}',
    '{@damage 1d6 + 2}',
    '{@damage 1d6 + 3 + summonSpellLevel}',
    '{@damage 1d6 + 3}',
    '{@damage 1d6 + 4 + summonSpellLevel}',
    '{@damage 1d6 + 4}',
    '{@damage 1d6 + 5}',
    '{@damage 1d6 + 6}',
    '{@damage 1d6 + 7}',
    '{@damage 1d6 + 8}',
    '{@damage 1d6 + 9}',
    '{@damage 1d6 + PB}',
    '{@damage 1d6 +2}',
    '{@damage 1d6}',
    '{@damage 1d6+2}',
    '{@damage 1d8 - 1}',
    '{@damage 1d8 -1}',
    '{@damage 1d8 + 1}',
    '{@damage 1d8 + 10}',
    '{@damage 1d8 + 12}',
    '{@damage 1d8 + 18}',
    '{@damage 1d8 + 2 + PB}',
    '{@damage 1d8 + 2}',
    '{@damage 1d8 + 3 + summonSpellLevel}',
    '{@damage 1d8 + 3}',
    '{@damage 1d8 + 4 + summonSpellLevel}',
    '{@damage 1d8 + 4}',
    '{@damage 1d8 + 5}',
    '{@damage 1d8 + 6}',
    '{@damage 1d8 + 7}',
    '{@damage 1d8 + 8}',
    '{@damage 1d8 + 9}',
    '{@damage 1d8 + PB}',
    '{@damage 1d8 + summonSpellLevel}',
    '{@damage 1d8}',
    '{@damage 20d6}',
    '{@damage 22d6}',
    '{@damage 26d6}',
    '{@damage 2d10 + 1}',
    '{@damage 2d10 + 10}',
    '{@damage 2d10 + 15}',
    '{@damage 2d10 + 2}',
    '{@damage 2d10 + 3}',
    '{@damage 2d10 + 4}',
    '{@damage 2d10 + 5}',
    '{@damage 2d10 + 6}',
    '{@damage 2d10 + 7}',
    '{@damage 2d10 + 8}',
    '{@damage 2d10 + 9}',
    '{@damage 2d10 + summonSpellLevel}',
    '{@damage 2d10}',
    '{@damage 2d12 + 10}',
    '{@damage 2d12 + 2}',
    '{@damage 2d12 + 3}',
    '{@damage 2d12 + 4}',
    '{@damage 2d12 + 5}',
    '{@damage 2d12 + 6}',
    '{@damage 2d12 + 7}',
    '{@damage 2d12 + 8}',
    '{@damage 2d12 + 9}',
    '{@damage 2d12}',
    '{@damage 2d4 + 1}',
    '{@damage 2d4 + 2}',
    '{@damage 2d4 + 3 + summonSpellLevel}',
    '{@damage 2d4 + 3}',
    '{@damage 2d4 + 4}',
    '{@damage 2d4 + 5}',
    '{@damage 2d4 + 6}',
    '{@damage 2d4 + 7}',
    '{@damage 2d4 + 8}',
    '{@damage 2d4 + 9}',
    '{@damage 2d4 + PB}',
    '{@damage 2d4}',
    '{@damage 2d6 + 1}',
    '{@damage 2d6 + 10}',
    '{@damage 2d6 + 15}',
    '{@damage 2d6 + 2 + summonSpellLevel}',
    '{@damage 2d6 + 2}',
    '{@damage 2d6 + 3 + summonSpellLevel}',
    '{@damage 2d6 + 3}',
    '{@damage 2d6 + 4}',
    '{@damage 2d6 + 5}',
    '{@damage 2d6 + 6}',
    '{@damage 2d6 + 7}',
    '{@damage 2d6 + 8}',
    '{@damage 2d6 + 9}',
    '{@damage 2d6}',
    '{@damage 2d8 + 1}',
    '{@damage 2d8 + 10}',
    '{@damage 2d8 + 11}',
    '{@damage 2d8 + 12}',
    '{@damage 2d8 + 15}',
    '{@damage 2d8 + 2}',
    '{@damage 2d8 + 3}',
    '{@damage 2d8 + 4}',
    '{@damage 2d8 + 5}',
    '{@damage 2d8 + 6}',
    '{@damage 2d8 + 7}',
    '{@damage 2d8 + 8}',
    '{@damage 2d8 + 9}',
    '{@damage 2d8}',
    '{@damage 3d10 + 1}',
    '{@damage 3d10 + 10}',
    '{@damage 3d10 + 2}',
    '{@damage 3d10 + 3}',
    '{@damage 3d10 + 4}',
    '{@damage 3d10 + 5}',
    '{@damage 3d10 + 6}',
    '{@damage 3d10 + 7}',
    '{@damage 3d10 + 8}',
    '{@damage 3d10 + 9}',
    '{@damage 3d10}',
    '{@damage 3d12 + 10}',
    '{@damage 3d12 + 11}',
    '{@damage 3d12 + 3}',
    '{@damage 3d12 + 4}',
    '{@damage 3d12 + 5}',
    '{@damage 3d12 + 6}',
    '{@damage 3d12 + 7}',
    '{@damage 3d12 + 8}',
    '{@damage 3d12 + 9}',
    '{@damage 3d12}',
    '{@damage 3d4 + 1}',
    '{@damage 3d4 + 12}',
    '{@damage 3d4 + 2}',
    '{@damage 3d4 + 3}',
    '{@damage 3d4 + 4}',
    '{@damage 3d4 + 5}',
    '{@damage 3d4 + 8}',
    '{@damage 3d4}',
    '{@damage 3d6 + 1}',
    '{@damage 3d6 + 10}',
    '{@damage 3d6 + 2}',
    '{@damage 3d6 + 3}',
    '{@damage 3d6 + 4}',
    '{@damage 3d6 + 5}',
    '{@damage 3d6 + 6}',
    '{@damage 3d6 + 7}',
    '{@damage 3d6 + 8}',
    '{@damage 3d6 + 9}',
    '{@damage 3d6}',
    '{@damage 3d6+3}',
    '{@damage 3d8 + 10}',
    '{@damage 3d8 + 11}',
    '{@damage 3d8 + 2}',
    '{@damage 3d8 + 3}',
    '{@damage 3d8 + 4}',
    '{@damage 3d8 + 5}',
    '{@damage 3d8 + 6}',
    '{@damage 3d8 + 7}',
    '{@damage 3d8 + 8}',
    '{@damage 3d8 + 9}',
    '{@damage 3d8}',
    '{@damage 4d10 + 10}',
    '{@damage 4d10 + 2}',
    '{@damage 4d10 + 3}',
    '{@damage 4d10 + 4}',
    '{@damage 4d10 + 5}',
    '{@damage 4d10 + 6}',
    '{@damage 4d10 + 7}',
    '{@damage 4d10 + 8}',
    '{@damage 4d10 + 9}',
    '{@damage 4d10}',
    '{@damage 4d12 + 10}',
    '{@damage 4d12 + 2}',
    '{@damage 4d12 + 4}',
    '{@damage 4d12 + 5}',
    '{@damage 4d12 + 6}',
    '{@damage 4d12 + 7}',
    '{@damage 4d12 + 9}',
    '{@damage 4d12}',
    '{@damage 4d4 + 2}',
    '{@damage 4d4 + 3}',
    '{@damage 4d4 + 4}',
    '{@damage 4d4 + 5}',
    '{@damage 4d4 + 7}',
    '{@damage 4d4}',
    '{@damage 4d6 + 10}',
    '{@damage 4d6 + 2}',
    '{@damage 4d6 + 3}',
    '{@damage 4d6 + 4}',
    '{@damage 4d6 + 5}',
    '{@damage 4d6 + 6}',
    '{@damage 4d6 + 7}',
    '{@damage 4d6 + 8}',
    '{@damage 4d6 + 9}',
    '{@damage 4d6}',
    '{@damage 4d8 + 10}',
    '{@damage 4d8 + 2}',
    '{@damage 4d8 + 3}',
    '{@damage 4d8 + 4}',
    '{@damage 4d8 + 5}',
    '{@damage 4d8 + 6}',
    '{@damage 4d8 + 7}',
    '{@damage 4d8 + 8}',
    '{@damage 4d8 + 9}',
    '{@damage 4d8}',
    '{@damage 5d10 + 4}',
    '{@damage 5d10 + 5}',
    '{@damage 5d10 + 6}',
    '{@damage 5d10 + 9}',
    '{@damage 5d10}',
    '{@damage 5d12 + 10}',
    '{@damage 5d12 + 2}',
    '{@damage 5d12 + 4}',
    '{@damage 5d12 + 6}',
    '{@damage 5d12 + 7}',
    '{@damage 5d12}',
    '{@damage 5d4 + 2}',
    '{@damage 5d4}',
    '{@damage 5d6 + 3}',
    '{@damage 5d6 + 4}',
    '{@damage 5d6 + 5}',
    '{@damage 5d6 + 6}',
    '{@damage 5d6 + 7}',
    '{@damage 5d6 + 8}',
    '{@damage 5d6}',
    '{@damage 5d8 + 4}',
    '{@damage 5d8 + 5}',
    '{@damage 5d8 + 6}',
    '{@damage 5d8 + 7}',
    '{@damage 5d8 + 8}',
    '{@damage 5d8}',
    '{@damage 6d10 + 10}',
    '{@damage 6d10 + 3}',
    '{@damage 6d10 + 4}',
    '{@damage 6d10 + 5}',
    '{@damage 6d10 + 7}',
    '{@damage 6d10}',
    '{@damage 6d12 + 4}',
    '{@damage 6d12 + 6}',
    '{@damage 6d12 + 8}',
    '{@damage 6d12}',
    '{@damage 6d4 + 6}',
    '{@damage 6d4}',
    '{@damage 6d6 + 1}',
    '{@damage 6d6 + 10}',
    '{@damage 6d6 + 16}',
    '{@damage 6d6 + 4}',
    '{@damage 6d6 + 5}',
    '{@damage 6d6 + 6}',
    '{@damage 6d6 + 7}',
    '{@damage 6d6 + 8}',
    '{@damage 6d6 + 9}',
    '{@damage 6d6}',
    '{@damage 6d8 + 10}',
    '{@damage 6d8 + 3}',
    '{@damage 6d8 + 4}',
    '{@damage 6d8 + 5}',
    '{@damage 6d8 + 6}',
    '{@damage 6d8 + 8}',
    '{@damage 6d8 + 9}',
    '{@damage 6d8}',
    '{@damage 7d10 + 7}',
    '{@damage 7d10 + 8}',
    '{@damage 7d10}',
    '{@damage 7d12}',
    '{@damage 7d6 + 4}',
    '{@damage 7d6 + 5}',
    '{@damage 7d6 + 6}',
    '{@damage 7d6 + 9}',
    '{@damage 7d6}',
    '{@damage 7d8 + 30}',
    '{@damage 7d8 + 4}',
    '{@damage 7d8}',
    '{@damage 8d10 + 5}',
    '{@damage 8d10 + 7}',
    '{@damage 8d10}',
    '{@damage 8d12 + 10}',
    '{@damage 8d12}',
    '{@damage 8d4 + 7}',
    '{@damage 8d6 + 10}',
    '{@damage 8d6 + 4}',
    '{@damage 8d6 + 7}',
    '{@damage 8d6 + 8}',
    '{@damage 8d6}',
    '{@damage 8d8 + 10}',
    '{@damage 8d8 + 5}',
    '{@damage 8d8 + 60}',
    '{@damage 8d8 + 7}',
    '{@damage 8d8 + 8}',
    '{@damage 8d8 + 9}',
    '{@damage 8d8}',
    '{@damage 9d10}',
    '{@damage 9d12 + 7}',
    '{@damage 9d12}',
    '{@damage 9d4 + 2}',
    '{@damage 9d6 + 1}',
    '{@damage 9d6 + 3}',
    '{@damage 9d6 + 5}',
    '{@damage 9d6 + 9}',
    '{@damage 9d6}',
    '{@damage 9d8}',
    '{@damage d10}',

    // Replace for the value adding before the letters DC
    '{@dc 0}',
    '{@dc 10}',
    '{@dc 11}',
    '{@dc 12}',
    '{@dc 13}',
    '{@dc 14}',
    '{@dc 15}',
    '{@dc 16}',
    '{@dc 17}',
    '{@dc 18}',
    '{@dc 19}',
    '{@dc 20}',
    '{@dc 21}',
    '{@dc 22}',
    '{@dc 23}',
    '{@dc 24}',
    '{@dc 25}',
    '{@dc 26}',
    '{@dc 27}',
    '{@dc 5}',
    '{@dc 6}',
    '{@dc 7}',
    '{@dc 8}',
    '{@dc 9}',

    // Just keep the text in italic, if | is found, stop there.
    '{@deity The Matron of Ravens|Exandria|TDCSR|Raven Queen\'s}',

    // Add the value between parenthesis.
    '{@dice 10d10}',
    '{@dice 10d6 + 20}',
    '{@dice 10d8 + 10}',
    '{@dice 10d8 + 20}',
    '{@dice 11d6 + 22}',
    '{@dice 11d8 + 11}',
    '{@dice 11d8 + 22}',
    '{@dice 12d6 + 24}',
    '{@dice 12d8 + 12}',
    '{@dice 12d8 + 24}',
    '{@dice 13d10}',
    '{@dice 17d8 + 51}',
    '{@dice 1d10 + 10}',
    '{@dice 1d10 + 11}',
    '{@dice 1d10 + 12}',
    '{@dice 1d10 + 2}',
    '{@dice 1d10 + 27}',
    '{@dice 1d10 + 3}',
    '{@dice 1d10 + 4}',
    '{@dice 1d10 + 6}',
    '{@dice 1d10 + 9}',
    '{@dice 1d10}',
    '{@dice 1d100}',
    '{@dice 1d12 + 2}',
    '{@dice 1d12 + 3}',
    '{@dice 1d12 + 4}',
    '{@dice 1d12}',
    '{@dice 1d2}',
    '{@dice 1d20 + 2}',
    '{@dice 1d20}',
    '{@dice 1d3 + 1}',
    '{@dice 1d3}',
    '{@dice 1d4 + 1}',
    '{@dice 1d4 + 2}',
    '{@dice 1d4 + 3}',
    '{@dice 1d4 + 4}',
    '{@dice 1d4 + 5}',
    '{@dice 1d4 × 10}',
    '{@dice 1d4 × 2}',
    '{@dice 1d4}',
    '{@dice 1d6 + 1}',
    '{@dice 1d6 + 2}',
    '{@dice 1d6 + 3}',
    '{@dice 1d6 + 4}',
    '{@dice 1d6}',
    '{@dice 1d8 + 1}',
    '{@dice 1d8 + 2}',
    '{@dice 1d8 + 3}',
    '{@dice 1d8 + 5}',
    '{@dice 1d8}',
    '{@dice 2d10 + 5}',
    '{@dice 2d10}',
    '{@dice 2d12 + 4}',
    '{@dice 2d12}',
    '{@dice 2d4 + 2}',
    '{@dice 2d4 × 10}',
    '{@dice 2d4}',
    '{@dice 2d6 + 1}',
    '{@dice 2d6}',
    '{@dice 2d8 + 2}',
    '{@dice 2d8 + 3}',
    '{@dice 2d8 + 4}',
    '{@dice 2d8 + 6}',
    '{@dice 2d8 + PB}',
    '{@dice 2d8 + summonSpellLevel}',
    '{@dice 2d8}',
    '{@dice 3d10}',
    '{@dice 3d6 + 6}',
    '{@dice 3d6 × 10}',
    '{@dice 3d6}',
    '{@dice 3d8 + 3}',
    '{@dice 3d8 + 5}',
    '{@dice 3d8 + 6}',
    '{@dice 3d8}',
    '{@dice 4d10}',
    '{@dice 4d12 + 4}',
    '{@dice 4d4 + 6}',
    '{@dice 4d6 + 8}',
    '{@dice 4d6}',
    '{@dice 4d8 + 2}',
    '{@dice 4d8 + 4}',
    '{@dice 4d8 + 8}',
    '{@dice 4d8}',
    '{@dice 5d10}',
    '{@dice 5d20}',
    '{@dice 5d4 + 6}',
    '{@dice 5d4}',
    '{@dice 5d6 + 10}',
    '{@dice 5d6 + 5}',
    '{@dice 5d6}',
    '{@dice 5d8 + 10}',
    '{@dice 5d8 + 5}',
    '{@dice 6d12}',
    '{@dice 6d6 + 12}',
    '{@dice 6d6}',
    '{@dice 6d8 + 12}',
    '{@dice 6d8 + 3}',
    '{@dice 6d8 + 6}',
    '{@dice 6d8}',
    '{@dice 7d6 + 14}',
    '{@dice 7d8 + 14}',
    '{@dice 7d8 + 7}',
    '{@dice 8d6 + 16}',
    '{@dice 8d8 + 16}',
    '{@dice 8d8 + 4}',
    '{@dice 8d8 + 8}',
    '{@dice 9d6 + 18}',
    '{@dice 9d8 + 18}',
    '{@dice 9d8 + 9}',
    '{@dice 9d8}',
    '{@dice d10}',
    '{@dice d100}',
    '{@dice d12}',
    '{@dice d20}',
    '{@dice d4}',
    '{@dice d6}',
    '{@dice d8}',

    // Just keep the text in italic, if | is found, stop there.
    '{@disease bluerot|GoS}',

    // Just keep the text in italic and add before (feat).
    '{@feat healer}',

    // Just keep the text in italic, if | is found, stop there.
    '{@filter 1st-level wizard spell|spells|level=1|class=wizard}',
    '{@filter an illusion spell of 4th level or lower|spells|school=I|level=0;1;2;3;4}',
    '{@filter another creature of CR 20 or lower that is not a construct or undead|bestiary|Challenge Rating=[0;&20]|type=!construct;!undead|source=null}',
    '{@filter beast|bestiary|type=beast|miscellaneous=!swarm}',
    '{@filter cleric spell up to 9th level|spells|level=0;1;2;3;4;5;6;7;8;9|class=cleric}',
    '{@filter demon of challenge rating 6 or lower|bestiary|challenge rating=[&0;&6]|tag=demon|miscellaneous=!swarm}',
    '{@filter necromancy or enchantment school that is 3rd level or lower|spells|level=0;1;2;3|school=N;E}',
    '{@filter necromancy or enchantment school that is 8th level or lower|spells|level=0;1;2;3;4;5;6;7;8|school=N;E}',
    '{@filter ooze|bestiary|type=ooze}',
    '{@filter supernatural charm|rewards|type=charm}',
    '{@filter Undead creatures|bestiary|type=undead}',

    // Just keep the text in italic, if | is found, stop there.
    '{@footnote one with its stomp, and one with its tail|{@note This statblock does not have these actions available.}',

    // Ignore
    '{@h}',
    '{@hazard burning|XPHB}',
    '{@hazard green slime}',

    // Replace for the value adding before the letters to hit.
    '{@hit -1}',
    '{@hit +13}',
    '{@hit +7}',
    '{@hit 0}',
    '{@hit 1}',
    '{@hit 10}',
    '{@hit 11}',
    '{@hit 12}',
    '{@hit 13}',
    '{@hit 14}',
    '{@hit 15}',
    '{@hit 16}',
    '{@hit 17}',
    '{@hit 18}',
    '{@hit 19}',
    '{@hit 2}',
    '{@hit 20}',
    '{@hit 21}',
    '{@hit 3}',
    '{@hit 4}',
    '{@hit 5}',
    '{@hit 6}',
    '{@hit 7}',
    '{@hit 8}',
    '{@hit 9}',

    // Just keep the text in italic, if | is found, stop there.
    '{@hitYourSpellAttack Bonus equals your spell attack modifier}',
    '{@hitYourSpellAttack}',

    // Ignore
    '{@hom}',

    // Just keep the text in italic, if | is found, stop there.
    '{@i Afterthought}',
    '{@i bolt of blinding}',
    '{@i bolt of holding}',
    '{@i bolt of vapors}',
    '{@i Fear of Its Own Reflection.}',
    '{@i Master Adranach Only; Recharges after a {@quickref resting|PHB|2|0|Long Rest}',
    '{@i Master Adranach Only}',
    '{@i Recharges after a {@quickref resting|PHB|2|0|Long Rest}',
    '{@i Susceptible to Holy Symbols.}',

    // Just keep the text in italic, if | is found, stop there.
    '{@item +1 breastplate}',
    '{@item +1 chain shirt}',
    '{@item +1 dagger}',
    '{@item +1 heavy crossbow}',
    '{@item +1 leather armor}',
    '{@item +1 longsword}',
    '{@item +1 maul}',
    '{@item +1 quarterstaff}',
    '{@item +1 scale mail}',
    '{@item +1 shield}',
    '{@item +1 shortsword}',
    '{@item +1 studded leather armor}',
    '{@item +1 Studded Leather Armor||+1 studded leather}',
    '{@item +2 dagger}',
    '{@item +2 Dagger}',
    '{@item +2 greatsword}',
    '{@item +2 leather armor}',
    '{@item +2 Longsword}',
    '{@item +2 plate armor}',
    '{@item +2 plate armor||+2 plate}',
    '{@item +2 ring of protection|TDCSR}',
    '{@item +2 ring of protection|TDCSR|ring of protection with a +2 bonus}',
    '{@item +2 Ring of Protection|TDCSR|ring of protection with a +2 bonus}',
    '{@item +2 Rod of the Pact Keeper||rod}',
    '{@item +2 shield}',
    '{@item +2 shortsword}',
    '{@item +2 Studded Leather Armor of Acid Resistance|TDCSR}',
    '{@item +2 Studded Leather Armor||+2 studded leather}',
    '{@item +2 Studded White Dragon Leather Armor of Cold Resistance|TDCSR}',
    '{@item +2 warhammer}',
    '{@item +3 greataxe}',
    '{@item +3 leather armor}',
    '{@item +3 mace}',
    '{@item +3 plate armor}',
    '{@item +3 rapier}',
    '{@item +3 scale mail}',
    '{@item Acid (vial)|phb|acid}',
    '{@item acid (vial)|PHB|flask of acid}',
    '{@item adamantine plate armor}',
    '{@item Alchemist\'s Fire (flask)|phb|alchemist\'s fire}',
    '{@item Alchemist\'s Fire (flask)|PHB|flask of alchemist\'s fire}',
    '{@item Alchemist\'s Supplies|phb|alchemical supplies}',
    '{@item amulet of proof against detection and location}',
    '{@item amulet of the black skull|ToA}',
    '{@item amulet of the planes}',
    '{@item arrow-catching shield}',
    '{@item Azuredge|wdh}',
    '{@item badge of the Watch|wdh}',
    '{@item Badge of the Watch|wdh}',
    '{@item bag of holding}',
    '{@item bead of force}',
    '{@item Bead of Force}',
    '{@item bead of force||beads of force}',
    '{@item belt of dwarvenkind}',
    '{@item belt of fire giant strength}',
    '{@item belt of giant strength}',
    '{@item Black Dragon Mask|hotdq}',
    '{@item Blackstaff|WDH}',
    '{@item blade of the medusa|LLK}',
    '{@item blast scepter|WDMM}',
    '{@item Bloodaxe|EGW}',
    '{@item Blue Dragon Mask|RoTOS}',
    '{@item Bookmark|toa}',
    '{@item boots of haste|TDCSR}',
    '{@item boots of levitation}',
    '{@item boots of speed}',
    '{@item boots of striding and springing}',
    '{@item bracer of flying daggers|wdh}',
    '{@item bracers of defense}',
    '{@item Bracers of Defense}',
    '{@item breastplate barding|phb}',
    '{@item breastplate|phb}',
    '{@item breastplate|PHB}',
    '{@item broom of flying}',
    '{@item Cabal\'s Ruin (Exalted)|TDCSR|Cabal\'s Ruin}',
    '{@item cape of the mountebank}',
    '{@item cartographer\'s tools|PHB}',
    '{@item chain mail barding|phb}',
    '{@item Chain mail barding|phb|Chain mail}',
    '{@item chain mail|phb}',
    '{@item chain mail|PHB}',
    '{@item chain shirt|phb}',
    '{@item chain shirt|PHB}',
    '{@item chime of opening}',
    '{@item circlet of blasting}',
    '{@item circlet of wisdom|TDCSR}',
    '{@item cloak of invisibility}',
    '{@item cloak of protection}',
    '{@item cloak of the manta ray}',
    '{@item Crown of Lies|VEoR}',
    '{@item crystal ball}',
    '{@item dagger|PHB|daggers}',
    '{@item Deathwalker\'s ward (Exalted)|TDCSR|Deathwalker\'s ward}',
    '{@item Deathwalker\'s Ward (Exalted)|TDCSR|Deathwalker\'s Ward}',
    '{@item Deck of Several Things|LLK}',
    '{@item dimensional shackles}',
    '{@item documancy satchel|AI}',
    '{@item dread helm|XGE}',
    '{@item drow +1 chain shirt|mm|+1 chain shirt}',
    '{@item drow +1 shortsword|mm|+1 shortsword}',
    '{@item drow +2 shortsword|mm|+2 shortsword}',
    '{@item drow +2 studded leather armor|mm|+2 studded leather armor}',
    '{@item drow +3 scale mail|MM|+3 scale mail}',
    '{@item Drown|PotA}',
    '{@item dwarven plate}',
    '{@item dwarven thrower}',
    '{@item Dwarven Thrower}',
    '{@item Eldritch Staff|WBtW}',
    '{@item elemental gem}',
    '{@item elven chain}',
    '{@item eyescratch|WDH}',
    '{@item Fane-Eater|BGDIA}',
    '{@item feather of diatryma summoning|wdh}',
    '{@item Fenthras (Exalted)|TDCSR|Fenthras}',
    '{@item Figurine of Wondrous Power, Silver Raven||figurine of wondrous power (silver raven)}',
    '{@item flame tongue longsword}',
    '{@item Flame Tongue}',
    '{@item Gambler\'s Blade longsword|LLK}',
    '{@item gauntlets of flaming fury|BGDIA}',
    '{@item gauntlets of ogre power}',
    '{@item Gauntlets of Ogre Power}',
    '{@item gem of seeing}',
    '{@item glamoured studded leather}',
    '{@item gloves of swimming and climbing}',
    '{@item Greatsword of Sharpness||sword of sharpness (greatsword)}',
    '{@item half plate armor|phb}',
    '{@item half plate armor|PHB}',
    '{@item half plate armor|phb|half plate}',
    '{@item half plate armor|PHB|half plate}',
    '{@item Hand of Vecna}',
    '{@item handaxe|PHB|40 handaxes}',
    '{@item hat of disguise}',
    '{@item Hazirawn|hotdq}',
    '{@item healer\'s kit|phb}',
    '{@item helm of brilliance}',
    '{@item herbalism kit|phb}',
    '{@item Heretic|QftIS}',
    '{@item hide armor of cold resistance}',
    '{@item hide armor|phb}',
    '{@item hide armor|PHB}',
    '{@item holy avenger longsword}',
    '{@item Holy Water (flask)|PHB|holy water}',
    '{@item holy water (flask)|phb|vials of holy water}',
    '{@item infernal tack|MTF}',
    '{@item insignia of claws|hotdq}',
    '{@item Ironfang|PotA}',
    '{@item knave\'s eye patch|wdh}',
    '{@item leather armor|phb}',
    '{@item leather armor|PHB}',
    '{@item leather armor|PHB|leather}',
    '{@item leather barding|phb}',
    '{@item Leather barding|phb|Leather}',
    '{@item mace of disruption}',
    '{@item Mace|PHB}',
    '{@item mariner\'s armor}',
    '{@item Mask of the Dragon Queen|rot}',
    '{@item Moonblade}',
    '{@item Mythcarver (Exalted)|TDCSR|Mythcarver}',
    '{@item necklace of fireballs}',
    '{@item Nepenthe|VRGR}',
    '{@item Nightbringer|MCV2DC}',
    '{@item nine lives stealer}',
    '{@item oathbow}',
    '{@item obsidian flint dragon plate|BGDIA}',
    '{@item Obsidian Flint Dragon Plate|BGDIA}',
    '{@item Orb of Direction|XGE}',
    '{@item Orb of Time|XGE}',
    '{@item plate armor of fire resistance}',
    '{@item plate armor|phb}',
    '{@item plate armor|PHB}',
    '{@item plate armor|phb|plate}',
    '{@item plate armor|PHB|plate}',
    '{@item plate barding|phb}',
    '{@item plate barding|PHB}',
    '{@item Plate barding|phb|Plate}',
    '{@item plate of the Dawnmartyr (exalted)|TDCSR|plate of the Dawnmartyr}',
    '{@item plate of the Dawnmartyr (exalted)|TDCSR|Plate of the Dawnmartyr}',
    '{@item polymorph blade|LLK}',
    '{@item portable hole}',
    '{@item potion of cold resistance||potions of resistance (cold)}',
    '{@item potion of fire resistance||potions of resistance (fire)}',
    '{@item potion of frost giant strength}',
    '{@item potion of greater healing||potions of greater healing}',
    '{@item potion of heroism||potions of heroism}',
    '{@item Potion of Hill Giant Strength||potion of giant strength (hill)}',
    '{@item potion of invisibility}',
    '{@item potion of invulnerability}',
    '{@item potion of lightning resistance||potions of resistance (lightning)}',
    '{@item potion of superior healing||potions of superior healing}',
    '{@item purple worm poison}',
    '{@item quiver of Ehlonna}',
    '{@item raven\'s slumber|TDCSR}',
    '{@item red dragon scale mail}',
    '{@item ring mail barding|phb}',
    '{@item Ring mail barding|phb|Ring mail}',
    '{@item ring mail|phb}',
    '{@item ring mail|PHB}',
    '{@item ring of animal influence}',
    '{@item ring of cold resistance}',
    '{@item ring of feather falling}',
    '{@item ring of fire resistance}',
    '{@item Ring of Fire Resistance}',
    '{@item ring of force resistance||ring of resistance (force)}',
    '{@item ring of invisibility}',
    '{@item ring of lightning resistance}',
    '{@item ring of mind shielding}',
    '{@item ring of obscuring|EGW}',
    '{@item ring of protection}',
    '{@item Ring of Protection}',
    '{@item ring of regeneration}',
    '{@item Ring of Resistance}',
    '{@item ring of spell turning}',
    '{@item ring of swimming}',
    '{@item ring of the ram}',
    '{@item ring of truth telling|wdh}',
    '{@item ring of warmth}',
    '{@item Ring of Warmth}',
    '{@item Ring of Winter|toa}',
    '{@item robe of eyes}',
    '{@item Robe of Scintillating Colors}',
    '{@item robe of serpents|skt}',
    '{@item robe of stars}',
    '{@item robe of the archmagi}',
    '{@item Robe of the Archmagi}',
    '{@item robe of useful items}',
    '{@item robes|phb}',
    '{@item rod of lordly might}',
    '{@item rod of mercurial form|TDCSR}',
    '{@item rod of retribution|egw}',
    '{@item rod of rulership}',
    '{@item rope of entanglement}',
    '{@item Ruinblade|IMR}',
    '{@item scale mail barding|phb}',
    '{@item Scale mail barding|phb|Scale mail}',
    '{@item scale mail|phb}',
    '{@item scale mail|PHB}',
    '{@item scimitar of speed}',
    '{@item sending stones}',
    '{@item Sending Stones}',
    '{@item sending stones||sending stone}',
    '{@item Shatterspike|TftYP}',
    '{@item shield|phb}',
    '{@item shield|PHB}',
    '{@item shield|phb|Dual Shields}',
    '{@item shield|phb|shields}',
    '{@item skysail|TDCSR}',
    '{@item skysail|TDCSR|skysail\'s}',
    '{@item soul coin|BGDIA}',
    '{@item spell scroll (1st level)||scrolls}',
    '{@item Spell Scroll (2nd Level)||spell scroll}',
    '{@item spell scroll (5th level)||spell scroll}',
    '{@item spell scroll}',
    '{@item spellbook|phb}',
    '{@item Sphere of Annihilation}',
    '{@item spider staff|LMoP}',
    '{@item Spies\' Murmur|GGR|spies\' murmur}',
    '{@item Spire of Conflux (Exalted)|TDCSR|Spire of Conflux}',
    '{@item splint armor|phb}',
    '{@item splint armor|PHB|splint}',
    '{@item splint barding|phb}',
    '{@item Splint barding|phb|Splint}',
    '{@item staff of defense|PaBTSO}',
    '{@item staff of fire}',
    '{@item staff of frost}',
    '{@item staff of power}',
    '{@item Staff of Power}',
    '{@item staff of striking}',
    '{@item staff of swarming insects}',
    '{@item staff of the adder}',
    '{@item Staff of the Forgotten One|ToA}',
    '{@item Steel|WBtW}',
    '{@item studded leather armor|PHB}',
    '{@item studded leather armor|phb|studded leather}',
    '{@item studded leather armor|PHB|studded leather}',
    '{@item studded leather barding|phb}',
    '{@item Studded leather barding|phb|Studded leather}',
    '{@item sword of wounding|DMG|this weapon\'s}',
    '{@item talarith|BAM}',
    '{@item Talisman of the Sphere}',
    '{@item tentacle rod}',
    '{@item tentacle rod|DMG|rod}',
    '{@item Thessaltoxin|IMR|thessaltoxin poison}',
    '{@item thieves\' tools|phb}',
    '{@item thieves\' tools|PHB}',
    '{@item Titanstone Knuckles (Exalted)|TDCSR|Titanstone Knuckles}',
    '{@item vorpal sword}',
    '{@item wand of fireballs}',
    '{@item wand of lightning bolts}',
    '{@item wand of magic detection}',
    '{@item wand of magic missiles}',
    '{@item Wand of Orcus}',
    '{@item wand of web}',
    '{@item wand of winter|hotdq}',
    '{@item wand of wonder}',
    '{@item wand of wonder||randomly determined effects}',
    '{@item Wave}',
    '{@item whip|phb}',
    '{@item Whisper (Exalted)|TDCSR|Whisper}',
    '{@item winged boots}',
    '{@item Winged Boots}',
    '{@item Witchlight vane|WbtW}',
    '{@item Witchlight watch|WbtW}',
    '{@item woodcarver\'s tools|PHB}',
    '{@item wrought-iron tower|CoA}',

    // Just keep the text in italic, if | is found, stop there.
    '{@note See the "Variant: Dragons as Innate Spellcasters" inset(s), below.}',
    '{@note The {@creature Mage|MM}',
    '{@note The {@creature Priest|MM}',
    '{@note This trait applies when two guardians are chained together.}',

    // Just keep the text in italic, if | is found, stop there.
    '{@quickref ability checks|PHB|2|0}',
    '{@quickref Advantage and Disadvantage|PHB|2|0|advantage}',
    '{@quickref Advantage and Disadvantage|PHB|2|0|disadvantage}',
    '{@quickref cover||3||half cover}',
    '{@quickref Cover||3||half cover}',
    '{@quickref cover||3||three-quarters cover}',
    '{@quickref Cover||3||three-quarters cover}',
    '{@quickref cover||3||total cover}',
    '{@quickref Cover||3||total cover}',
    '{@quickref Cover||3||Total cover}',
    '{@quickref difficult terrain||3}',
    '{@quickref falling|XGE|2|0|falling damage}',
    '{@quickref jumping|PHB|4|0|high jump}',
    '{@quickref jumping|PHB|4|0|jumps}',
    '{@quickref jumping|PHB|4|0|long jump}',
    '{@quickref resting|PHB|2|0|Long Rest}',
    '{@quickref resting|PHB|2|0|short or long rest}',
    '{@quickref resting|PHB|2|0|Short or Long rest}',
    '{@quickref resting|PHB|2|0|Short or Long Rest}',
    '{@quickref resting|PHB|2|0|Short Rest}',
    '{@quickref saving throws|PHB|2|1}',
    '{@quickref saving throws|PHB|2|1|saving throw}',
    '{@quickref Underwater Combat|PHB|3|0|underwater}',

    // Replace for the value adding before the letters recharge.
    '{@recharge 4}',
    '{@recharge 5}',
    '{@recharge 5|m}',
    '{@recharge 6}',
    '{@recharge}',

    // Just keep the text in italic, if | is found, stop there.
    '{@sense blindsight}',
    '{@sense darkvision}',
    '{@sense tremorsense|MM}',
    '{@sense truesight}',

    // Just keep the text in italic, if | is found, ad the text after between parenthesis.
    '{@skill Acrobatics}',
    '{@skill Animal Handling}',
    '{@skill Arcana}',
    '{@skill Athletics}',
    '{@skill Athletics|XPHB}',
    '{@skill Deception}',
    '{@skill History}',
    '{@skill Insight}',
    '{@skill Insight|XPHB}',
    '{@skill Intimidation}',
    '{@skill Investigation}',
    '{@skill Medicine}',
    '{@skill Medicine|XPHB}',
    '{@skill Nature}',
    '{@skill Perception}',
    '{@skill Perception|XPHB}',
    '{@skill Performance}',
    '{@skill Persuasion}',
    '{@skill Persuasion|XPHB}',
    '{@skill Sleight of Hand}',
    '{@skill Stealth}',
    '{@skill Survival}',

    // Just keep the text in italic, if | is found, stop there.
    '{@skillCheck acrobatics 6}',
    '{@skillCheck animal_handling 5}',
    '{@skillCheck arcana 5}',
    '{@skillCheck athletics 4}',
    '{@skillCheck medicine 5}',
    '{@skillCheck performance 5}',

    // Link to the spell in the spellbook.
    '{@spell abi-dalzim\'s horrid wilting|XGE}',
    '{@spell absorb elements|XGE}',
    '{@spell acid splash}',
    '{@spell Acid Splash}',
    '{@spell aid}',
    '{@spell alarm}',
    '{@spell alter self}',
    '{@spell Alter Self}',
    '{@spell Alter Self|XPHB}',
    '{@spell animal friendship}',
    '{@spell Animal Friendship|XPHB}',
    '{@spell animal messenger}',
    '{@spell Animal Messenger|XPHB}',
    '{@spell animal shapes}',
    '{@spell Animal Shapes|XPHB}',
    '{@spell animate dead}',
    '{@spell Animate Dead}',
    '{@spell Animate Dead|XPHB}',
    '{@spell animate objects}',
    '{@spell antilife shell}',
    '{@spell Antilife Shell}',
    '{@spell antimagic field}',
    '{@spell Antimagic Field}',
    '{@spell Antimagic Field|XPHB}',
    '{@spell arcane eye}',
    '{@spell Arcane Eye}',
    '{@spell Arcane Eye|XPHB}',
    '{@spell arcane gate}',
    '{@spell arcane lock}',
    '{@spell Arcane Lock}',
    '{@spell armor of Agathys}',
    '{@spell arms of Hadar}',
    '{@spell astral projection}',
    '{@spell Astral Projection}',
    '{@spell Astral Projection|XPHB}',
    '{@spell augury}',
    '{@spell Augury}',
    '{@spell Augury|XPHB}',
    '{@spell Aura of Purity}',
    '{@spell awaken}',
    '{@spell Awaken}',
    '{@spell Awaken|XPHB}',
    '{@spell bane}',
    '{@spell Bane}',
    '{@spell banishing smite}',
    '{@spell banishment}',
    '{@spell barkskin}',
    '{@spell beacon of hope}',
    '{@spell beast sense}',
    '{@spell Befuddlement|XPHB}',
    '{@spell bestow curse}',
    '{@spell Bestow Curse}',
    '{@spell Bigby\'s hand}',
    '{@spell bigby\'s hand||arcane hand}',
    '{@spell Bigby\'s Hand||arcane hand}',
    '{@spell blade barrier}',
    '{@spell Blade Barrier}',
    '{@spell blade ward}',
    '{@spell bless}',
    '{@spell Bless}',
    '{@spell Bless|XPHB}',
    '{@spell blight}',
    '{@spell Blight}',
    '{@spell Blight|XPHB}',
    '{@spell blinding smite}',
    '{@spell blindness/deafness}',
    '{@spell Blindness/Deafness}',
    '{@spell Blindness/Deafness|XPHB}',
    '{@spell blink}',
    '{@spell Blink}',
    '{@spell blur}',
    '{@spell branding smite}',
    '{@spell burning hands}',
    '{@spell Burning Hands}',
    '{@spell call lightning}',
    '{@spell calm emotions}',
    '{@spell Calm Emotions}',
    '{@spell Calm Emotions|XPHB}',
    '{@spell chain lightning}',
    '{@spell Chain Lightning}',
    '{@spell Chain Lightning|XPHB}',
    '{@spell chaos bolt|XGE}',
    '{@spell charm monster|XGE}',
    '{@spell Charm Monster|XPHB}',
    '{@spell charm person}',
    '{@spell Charm Person}',
    '{@spell Charm Person|XPHB}',
    '{@spell chill touch}',
    '{@spell chromatic orb}',
    '{@spell circle of death}',
    '{@spell clairvoyance}',
    '{@spell Clairvoyance|XPHB}',
    '{@spell clone}',
    '{@spell cloud of daggers}',
    '{@spell cloudkill}',
    '{@spell Cloudkill}',
    '{@spell Cloudkill|XPHB}',
    '{@spell color spray}',
    '{@spell command}',
    '{@spell Command}',
    '{@spell Command|XPHB}',
    '{@spell commune with nature}',
    '{@spell commune}',
    '{@spell Commune}',
    '{@spell Commune|XPHB}',
    '{@spell compelled duel}',
    '{@spell Compelled Duel}',
    '{@spell comprehend languages}',
    '{@spell Comprehend Languages}',
    '{@spell compulsion}',
    '{@spell cone of cold}',
    '{@spell Cone of Cold}',
    '{@spell Cone of Cold|XPHB}',
    '{@spell confusion}',
    '{@spell Confusion}',
    '{@spell Confusion|XPHB}',
    '{@spell conjure animals}',
    '{@spell conjure elemental}',
    '{@spell conjure fey}',
    '{@spell conjure minor elementals}',
    '{@spell conjure woodland beings}',
    '{@spell contact other plane}',
    '{@spell Contact Other Plane}',
    '{@spell Contact Other Plane|XPHB}',
    '{@spell contagion}',
    '{@spell Contagion}',
    '{@spell contingency}',
    '{@spell continual flame}',
    '{@spell control flames|xge}',
    '{@spell control water}',
    '{@spell Control Water|XPHB}',
    '{@spell control weather}',
    '{@spell Control Weather|XPHB}',
    '{@spell cordon of arrows}',
    '{@spell counterspell}',
    '{@spell Counterspell|XPHB}',
    '{@spell create bonfire|xge}',
    '{@spell create food and water}',
    '{@spell Create Food and Water}',
    '{@spell Create Food and Water|XPHB}',
    '{@spell create or destroy water}',
    '{@spell Create or Destroy Water|XPHB}',
    '{@spell create undead}',
    '{@spell Create Undead|XPHB}',
    '{@spell creation}',
    '{@spell Creation|XPHB}',
    '{@spell crown of madness}',
    '{@spell Crown of Madness}',
    '{@spell crusader\'s mantle}',
    '{@spell Crusader\'s Mantle}',
    '{@spell cure wounds}',
    '{@spell Cure Wounds}',
    '{@spell Cure Wounds|XPHB}',
    '{@spell dancing lights}',
    '{@spell Dancing Lights}',
    '{@spell Dancing Lights|XPHB}',
    '{@spell darkness}',
    '{@spell Darkness}',
    '{@spell Darkness|XPHB}',
    '{@spell darkvision}',
    '{@spell daylight}',
    '{@spell Daylight}',
    '{@spell Daylight|XPHB}',
    '{@spell death ward}',
    '{@spell Death Ward}',
    '{@spell delayed blast fireball}',
    '{@spell demiplane}',
    '{@spell destructive wave}',
    '{@spell Destructive Wave|XPHB}',
    '{@spell detect evil and good}',
    '{@spell Detect Evil and Good}',
    '{@spell Detect Evil and Good|XPHB}',
    '{@spell detect magic}',
    '{@spell Detect Magic}',
    '{@spell Detect Magic|XPHB}',
    '{@spell detect poison and disease}',
    '{@spell detect thoughts}',
    '{@spell Detect Thoughts}',
    '{@spell Detect Thoughts|XPHB}',
    '{@spell dimension door}',
    '{@spell Dimension Door}',
    '{@spell Dimension Door|XPHB}',
    '{@spell disguise self}',
    '{@spell Disguise Self}',
    '{@spell Disguise Self|XPHB}',
    '{@spell disintegrate}',
    '{@spell dispel evil and good}',
    '{@spell Dispel Evil and Good}',
    '{@spell Dispel Evil and Good|XPHB}',
    '{@spell dispel magic}',
    '{@spell Dispel Magic}',
    '{@spell Dispel Magic|XPHB}',
    '{@spell dissonant whispers}',
    '{@spell distort value|AI}',
    '{@spell divination}',
    '{@spell Divination}',
    '{@spell Divination|XPHB}',
    '{@spell divine favor}',
    '{@spell divine word}',
    '{@spell dominate beast}',
    '{@spell dominate monster}',
    '{@spell Dominate Monster}',
    '{@spell Dominate Monster|XPHB}',
    '{@spell dominate person}',
    '{@spell Dominate Person}',
    '{@spell Dominate Person|XPHB}',
    '{@spell Drawmij\'s instant summons}',
    '{@spell dream}',
    '{@spell Dream|XPHB}',
    '{@spell druidcraft}',
    '{@spell Druidcraft}',
    '{@spell Druidcraft|XPHB}',
    '{@spell dust devil|xge}',
    '{@spell earth tremor|xge}',
    '{@spell earthquake}',
    '{@spell Earthquake}',
    '{@spell eldritch blast}',
    '{@spell elemental weapon}',
    '{@spell Elementalism|XPHB}',
    '{@spell encode thoughts|GGR}',
    '{@spell enervation|XGE}',
    '{@spell enhance ability}',
    '{@spell enlarge/reduce}',
    '{@spell ensnaring strike}',
    '{@spell entangle}',
    '{@spell Entangle|XPHB}',
    '{@spell enthrall}',
    '{@spell Enthrall}',
    '{@spell erupting earth|xge}',
    '{@spell etherealness}',
    '{@spell Etherealness}',
    '{@spell Etherealness|XPHB}',
    '{@spell Evard\'s black tentacles}',
    '{@spell Evard\'s Black Tentacles}',
    '{@spell expeditious retreat}',
    '{@spell eyebite}',
    '{@spell fabricate}',
    '{@spell Fabricate}',
    '{@spell faerie fire}',
    '{@spell Faerie Fire}',
    '{@spell Faerie Fire|XPHB}',
    '{@spell false life}',
    '{@spell False Life}',
    '{@spell fast friends|AI}',
    '{@spell fear}',
    '{@spell Fear|XPHB}',
    '{@spell feather fall}',
    '{@spell Feather Fall|XPHB}',
    '{@spell feeblemind}',
    '{@spell feign death}',
    '{@spell find familiar}',
    '{@spell Find Familiar|XPHB}',
    '{@spell find steed}',
    '{@spell Find Steed}',
    '{@spell find the path}',
    '{@spell finger of death}',
    '{@spell Finger of Death}',
    '{@spell Finger of Death|XPHB}',
    '{@spell fire bolt}',
    '{@spell Fire Bolt}',
    '{@spell fire shield}',
    '{@spell fire storm}',
    '{@spell Fire Storm}',
    '{@spell fireball}',
    '{@spell Fireball}',
    '{@spell Fireball|XPHB}',
    '{@spell flame arrows|XGE}',
    '{@spell flame blade}',
    '{@spell flame strike}',
    '{@spell Flame Strike}',
    '{@spell Flame Strike|XPHB}',
    '{@spell flaming sphere}',
    '{@spell flesh to stone}',
    '{@spell flesh to stone||flesh to ice}',
    '{@spell fly}',
    '{@spell Fly}',
    '{@spell Fly|XPHB}',
    '{@spell fog cloud}',
    '{@spell Fog cloud}',
    '{@spell Fog Cloud}',
    '{@spell Fog Cloud|XPHB}',
    '{@spell forbiddance}',
    '{@spell forcecage}',
    '{@spell foresight}',
    '{@spell Foresight}',
    '{@spell freedom of movement}',
    '{@spell Freedom of Movement}',
    '{@spell friends}',
    '{@spell frostbite|XGE}',
    '{@spell gaseous form}',
    '{@spell Gaseous Form}',
    '{@spell Gaseous Form|XPHB}',
    '{@spell gate}',
    '{@spell Gate}',
    '{@spell geas}',
    '{@spell Geas}',
    '{@spell Geas|XPHB}',
    '{@spell gentle repose}',
    '{@spell Gentle Repose}',
    '{@spell giant insect}',
    '{@spell gift of gab|AI}',
    '{@spell globe of invulnerability}',
    '{@spell Globe of Invulnerability}',
    '{@spell glyph of warding}',
    '{@spell goodberry}',
    '{@spell Goodberry}',
    '{@spell grasping vine}',
    '{@spell grease}',
    '{@spell Grease|XPHB}',
    '{@spell greater invisibility}',
    '{@spell Greater Invisibility}',
    '{@spell Greater Invisibility|XPHB}',
    '{@spell greater restoration}',
    '{@spell Greater restoration}',
    '{@spell Greater Restoration}',
    '{@spell Greater Restoration|XPHB}',
    '{@spell guardian of faith}',
    '{@spell guidance}',
    '{@spell Guidance}',
    '{@spell guiding bolt}',
    '{@spell Guiding Bolt|XPHB}',
    '{@spell gust of wind}',
    '{@spell Gust of Wind}',
    '{@spell Gust of Wind|XPHB}',
    '{@spell gust|xge}',
    '{@spell hail of thorns}',
    '{@spell hallow}',
    '{@spell Hallow}',
    '{@spell hallucinatory terrain}',
    '{@spell Hallucinatory Terrain|XPHB}',
    '{@spell harm}',
    '{@spell Harm}',
    '{@spell Harm|XPHB}',
    '{@spell haste}',
    '{@spell heal}',
    '{@spell Heal}',
    '{@spell healing word}',
    '{@spell Healing Word}',
    '{@spell Healing Word|XPHB}',
    '{@spell heat metal}',
    '{@spell Heat Metal}',
    '{@spell Heat Metal|XPHB}',
    '{@spell hellish rebuke}',
    '{@spell Hellish Rebuke|XPHB}',
    '{@spell heroes\' feast}',
    '{@spell Heroes\' Feast}',
    '{@spell Heroes\' Feast|XPHB}',
    '{@spell heroism}',
    '{@spell Heroism}',
    '{@spell hex}',
    '{@spell hold monster}',
    '{@spell Hold Monster}',
    '{@spell Hold Monster|XPHB}',
    '{@spell hold person}',
    '{@spell Hold Person}',
    '{@spell Hold Person|XPHB}',
    '{@spell holy aura}',
    '{@spell hunger of Hadar}',
    '{@spell Hunger of Hadar|XPHB}',
    '{@spell hunter\'s mark}',
    '{@spell hypnotic pattern}',
    '{@spell Hypnotic Pattern}',
    '{@spell Hypnotic Pattern|XPHB}',
    '{@spell ice knife|xge}',
    '{@spell Ice Knife|XPHB}',
    '{@spell ice storm}',
    '{@spell Ice Storm}',
    '{@spell Ice Storm|XPHB}',
    '{@spell identify}',
    '{@spell Identify}',
    '{@spell Identify|XPHB}',
    '{@spell illusory script}',
    '{@spell immolation|xge}',
    '{@spell imprisonment}',
    '{@spell Imprisonment}',
    '{@spell incendiary cloud}',
    '{@spell Incendiary Cloud}',
    '{@spell incite greed|AI}',
    '{@spell inflict wounds}',
    '{@spell insect plague}',
    '{@spell Insect Plague}',
    '{@spell Insect Plague|XPHB}',
    '{@spell invisibility}',
    '{@spell Invisibility}',
    '{@spell Invisibility|XPHB}',
    '{@spell Jallarzi\'s Storm of Radiance|XPHB}',
    '{@spell Jim\'s glowing coin|AI}',
    '{@spell Jim\'s magic missile|AI}',
    '{@spell jump}',
    '{@spell Jump|XPHB}',
    '{@spell knock}',
    '{@spell legend lore}',
    '{@spell Legend Lore}',
    '{@spell Legend Lore|XPHB}',
    '{@spell Leomund\'s tiny hut}',
    '{@spell lesser restoration}',
    '{@spell Lesser Restoration}',
    '{@spell Lesser Restoration|XPHB}',
    '{@spell levitate}',
    '{@spell Levitate}',
    '{@spell light}',
    '{@spell Light}',
    '{@spell Light|XPHB}',
    '{@spell lightning arrow}',
    '{@spell lightning bolt}',
    '{@spell Lightning Bolt}',
    '{@spell Lightning Bolt|XPHB}',
    '{@spell locate animals or plants}',
    '{@spell locate creature}',
    '{@spell Locate Creature}',
    '{@spell locate object}',
    '{@spell Locate Object}',
    '{@spell Locate Object|XPHB}',
    '{@spell longstrider}',
    '{@spell Longstrider|XPHB}',
    '{@spell maelstrom|XGE}',
    '{@spell mage armor}',
    '{@spell Mage Armor}',
    '{@spell Mage Armor|XPHB}',
    '{@spell mage hand}',
    '{@spell Mage Hand}',
    '{@spell Mage Hand|XPHB}',
    '{@spell magic circle}',
    '{@spell Magic Circle|XPHB}',
    '{@spell magic missile}',
    '{@spell Magic Missile}',
    '{@spell Magic Missile|XPHB}',
    '{@spell magic mouth}',
    '{@spell magic weapon}',
    '{@spell major image}',
    '{@spell Major Image}',
    '{@spell Major Image|XPHB}',
    '{@spell mass cure wounds}',
    '{@spell Mass Cure Wounds}',
    '{@spell mass heal}',
    '{@spell Mass Heal}',
    '{@spell mass healing word}',
    '{@spell mass suggestion}',
    '{@spell Mass Suggestion}',
    '{@spell Mass Suggestion|XPHB}',
    '{@spell Maximilian\'s earthen grasp|xge}',
    '{@spell maze}',
    '{@spell Maze}',
    '{@spell meld into stone}',
    '{@spell Meld into Stone|XPHB}',
    '{@spell Melf\'s acid arrow}',
    '{@spell Melf\'s Acid Arrow|XPHB}',
    '{@spell mending}',
    '{@spell Mending}',
    '{@spell Mending|XPHB}',
    '{@spell mental prison|XGE}',
    '{@spell message}',
    '{@spell Message}',
    '{@spell Message|XPHB}',
    '{@spell meteor swarm}',
    '{@spell Meteor Swarm}',
    '{@spell mind blank}',
    '{@spell Mind Blank|XPHB}',
    '{@spell Mind Spike|XPHB}',
    '{@spell minor illusion}',
    '{@spell Minor Illusion}',
    '{@spell Minor Illusion|XPHB}',
    '{@spell mirage arcane}',
    '{@spell mirror image}',
    '{@spell Mirror Image}',
    '{@spell Mirror Image|XPHB}',
    '{@spell mislead}',
    '{@spell Mislead}',
    '{@spell misty step}',
    '{@spell Misty Step|XPHB}',
    '{@spell modify memory}',
    '{@spell Modify Memory|XPHB}',
    '{@spell mold earth|xge}',
    '{@spell moonbeam}',
    '{@spell Moonbeam|XPHB}',
    '{@spell Mordenkainen\'s faithful hound}',
    '{@spell Mordenkainen\'s magnificent mansion}',
    '{@spell Mordenkainen\'s Magnificent Mansion||magnificent mansion}',
    '{@spell Mordenkainen\'s sword}',
    '{@spell move earth}',
    '{@spell Move Earth}',
    '{@spell Move Earth|XPHB}',
    '{@spell nondetection}',
    '{@spell Nondetection}',
    '{@spell Nondetection|XPHB}',
    '{@spell Nystul\'s magic aura}',
    '{@spell otiluke\'s freezing sphere}',
    '{@spell Otiluke\'s freezing sphere}',
    '{@spell Otiluke\'s resilient sphere}',
    '{@spell Otiluke\'s Resilient Sphere}',
    '{@spell Otiluke\'s Resilient Sphere||resilient sphere}',
    '{@spell Otto\'s irresistible dance}',
    '{@spell pass without trace}',
    '{@spell Pass without Trace}',
    '{@spell Pass Without Trace}',
    '{@spell Pass without Trace|XPHB}',
    '{@spell passwall}',
    '{@spell Passwall|XPHB}',
    '{@spell phantasmal force}',
    '{@spell Phantasmal Force}',
    '{@spell phantasmal killer}',
    '{@spell Phantasmal Killer|XPHB}',
    '{@spell phantom steed}',
    '{@spell Phantom Steed|XPHB}',
    '{@spell planar ally}',
    '{@spell planar binding}',
    '{@spell plane shift}',
    '{@spell Plane Shift}',
    '{@spell Plane Shift|XPHB}',
    '{@spell plant growth}',
    '{@spell Plant Growth}',
    '{@spell poison spray}',
    '{@spell polymorph}',
    '{@spell Polymorph}',
    '{@spell polymorph|phb|polymorphs}',
    '{@spell Polymorph|XPHB}',
    '{@spell power word kill}',
    '{@spell Power Word Kill|XPHB}',
    '{@spell power word stun}',
    '{@spell Power Word Stun|XPHB}',
    '{@spell prayer of healing}',
    '{@spell prestidigitation}',
    '{@spell Prestidigitation}',
    '{@spell Prestidigitation|XPHB}',
    '{@spell prismatic spray}',
    '{@spell Prismatic Spray}',
    '{@spell prismatic wall}',
    '{@spell Prismatic Wall}',
    '{@spell produce flame}',
    '{@spell programmed illusion}',
    '{@spell project image}',
    '{@spell Project Image|XPHB}',
    '{@spell protection from energy}',
    '{@spell protection from evil and good}',
    '{@spell Protection from Evil and Good}',
    '{@spell Protection from Evil and Good|XPHB}',
    '{@spell protection from poison}',
    '{@spell purify food and drink}',
    '{@spell Purify Food and Drink}',
    '{@spell Purify Food and Drink|XPHB}',
    '{@spell raise dead}',
    '{@spell Raise Dead}',
    '{@spell Raise Dead|XPHB}',
    '{@spell Rary\'s telepathic bond}',
    '{@spell ray of enfeeblement}',
    '{@spell ray of frost}',
    '{@spell ray of sickness}',
    '{@spell Ray of Sickness|XPHB}',
    '{@spell regenerate}',
    '{@spell Regenerate}',
    '{@spell remove curse}',
    '{@spell Remove Curse}',
    '{@spell Remove Curse|XPHB}',
    '{@spell resistance}',
    '{@spell Resistance}',
    '{@spell resurrection}',
    '{@spell Resurrection}',
    '{@spell Resurrection|XPHB}',
    '{@spell reverse gravity}',
    '{@spell revivify}',
    '{@spell Revivify}',
    '{@spell rope trick}',
    '{@spell sacred flame}',
    '{@spell Sacred Flame}',
    '{@spell sanctuary}',
    '{@spell Sanctuary|XPHB}',
    '{@spell scorching ray}',
    '{@spell Scorching Ray|XPHB}',
    '{@spell scrying}',
    '{@spell Scrying}',
    '{@spell Scrying|XPHB}',
    '{@spell searing smite}',
    '{@spell see invisibility}',
    '{@spell See Invisibility|XPHB}',
    '{@spell seeming}',
    '{@spell sending}',
    '{@spell Sending}',
    '{@spell Sending|XPHB}',
    '{@spell sequester}',
    '{@spell shape water|xge}',
    '{@spell shape water|XGE}',
    '{@spell shapechange}',
    '{@spell Shapechange|XPHB}',
    '{@spell shatter}',
    '{@spell Shatter}',
    '{@spell Shatter|XPHB}',
    '{@spell shield of faith}',
    '{@spell Shield of Faith}',
    '{@spell Shield of Faith|XPHB}',
    '{@spell shield}',
    '{@spell Shield|XPHB}',
    '{@spell shillelagh}',
    '{@spell shocking grasp}',
    '{@spell Shocking Grasp}',
    '{@spell silence}',
    '{@spell Silence}',
    '{@spell silent image}',
    '{@spell Silent Image}',
    '{@spell simulacrum}',
    '{@spell sleep}',
    '{@spell Sleep|XPHB}',
    '{@spell sleet storm}',
    '{@spell slow}',
    '{@spell Slow}',
    '{@spell Slow|XPHB}',
    '{@spell spare the dying}',
    '{@spell Spare the Dying}',
    '{@spell speak with animals}',
    '{@spell Speak with Animals}',
    '{@spell Speak with Animals|XPHB}',
    '{@spell speak with dead}',
    '{@spell Speak with Dead}',
    '{@spell Speak with Dead|XPHB}',
    '{@spell speak with plants}',
    '{@spell Speak with Plants}',
    '{@spell Speak with Plants|XPHB}',
    '{@spell spider climb}',
    '{@spell spike growth}',
    '{@spell Spike Growth}',
    '{@spell Spike Growth|XPHB}',
    '{@spell spirit guardians}',
    '{@spell Spirit Guardians|XPHB}',
    '{@spell spiritual weapon}',
    '{@spell Spiritual Weapon}',
    '{@spell Spiritual Weapon|XPHB}',
    '{@spell staggering smite}',
    '{@spell stinking cloud}',
    '{@spell stone shape}',
    '{@spell Stone Shape}',
    '{@spell Stone Shape|XPHB}',
    '{@spell Stoneskin}',
    '{@spell stoneskin}',
    '{@spell storm of vengeance}',
    '{@spell storm sphere|xge}',
    '{@spell suggestion}',
    '{@spell Suggestion}',
    '{@spell Suggestion|XPHB}',
    '{@spell sunbeam}',
    '{@spell Sunburst|XPHB}',
    '{@spell symbol}',
    '{@spell Symbol}',
    '{@spell Synaptic Static|XPHB}',
    '{@spell Tasha\'s hideous laughter}',
    '{@spell Tasha\'s Hideous Laughter}',
    '{@spell Tasha\'s Hideous Laughter|XPHB}',
    '{@spell telekinesis}',
    '{@spell Telekinesis}',
    '{@spell Telekinesis|XPHB}',
    '{@spell Telepathy}',
    '{@spell teleport}',
    '{@spell Teleport}',
    '{@spell Teleport|XPHB}',
    '{@spell teleportation circle}',
    '{@spell Tenser\'s floating disk}',
    '{@spell Tenser\'s Floating Disk}',
    '{@spell thaumaturgy}',
    '{@spell Thaumaturgy}',
    '{@spell Thaumaturgy|XPHB}',
    '{@spell thorn whip}',
    '{@spell thunder step|XGE}',
    '{@spell thunderclap|XGE}',
    '{@spell thunderous smite}',
    '{@spell thunderwave}',
    '{@spell Thunderwave|XPHB}',
    '{@spell tidal wave|xge}',
    '{@spell tidal wave|XGE}',
    '{@spell time stop}',
    '{@spell Time Stop}',
    '{@spell tongues}',
    '{@spell Tongues}',
    '{@spell Tongues|XPHB}',
    '{@spell transport via plants}',
    '{@spell Transport via Plants}',
    '{@spell tree stride}',
    '{@spell true polymorph}',
    '{@spell true resurrection}',
    '{@spell true seeing}',
    '{@spell True Seeing}',
    '{@spell True Seeing|XPHB}',
    '{@spell true strike}',
    '{@spell unseen servant}',
    '{@spell Unseen Servant}',
    '{@spell Unseen Servant|XPHB}',
    '{@spell vampiric touch}',
    '{@spell Vampiric touch}',
    '{@spell vicious mockery}',
    '{@spell Vitriolic Sphere|XPHB}',
    '{@spell wall of fire}',
    '{@spell Wall of Fire}',
    '{@spell Wall of Fire|XPHB}',
    '{@spell wall of force}',
    '{@spell Wall of Force}',
    '{@spell wall of ice}',
    '{@spell Wall of Ice}',
    '{@spell Wall of Ice|XPHB}',
    '{@spell wall of stone}',
    '{@spell Wall of Stone}',
    '{@spell Wall of Stone|XPHB}',
    '{@spell wall of thorns}',
    '{@spell warding bond}',
    '{@spell water breathing}',
    '{@spell Water Breathing|XPHB}',
    '{@spell water walk}',
    '{@spell watery sphere|XGE}',
    '{@spell web}',
    '{@spell Web}',
    '{@spell Web|XPHB}',
    '{@spell weird}',
    '{@spell Weird}',
    '{@spell wind walk}',
    '{@spell Wind Walk}',
    '{@spell Wind Walk|XPHB}',
    '{@spell wind wall}',
    '{@spell wish}',
    '{@spell Wish}',
    '{@spell Wish|XPHB}',
    '{@spell witch bolt}',
    '{@spell word of recall}',
    '{@spell Word of Recall}',
    '{@spell Word of Recall|XPHB}',
    '{@spell wrathful smite}',
    '{@spell zone of truth}',
    '{@spell Zone of Truth|XPHB}',

    // Just keep the text in italic, if | is found, stop there.
    '{@status concentration}',
    '{@status concentration||concentrating}',
    '{@status Concentration|XPHB}',
    '{@status surprised}',

    // Just keep the text in italic, if | is found, stop there.
    '{@table short-term madness|DMG}',

    // Just keep the text in italic, if | is found, stop there.
    '{@table Wild Magic Surge|PHB}',

    // Just keep the text in italic, if | is found, stop there.
    '{@variantrule Advantage|XPHB}',
    '{@variantrule Bloodied|XPHB}',
    '{@variantrule Bonus Action|XPHB}',
    '{@variantrule Bright Light|XPHB}',
    '{@variantrule Burrow Speed|XPHB}',
    '{@variantrule Climb Speed|XPHB}',
    '{@variantrule Cone [Area of Effect]|XPHB|Cone}',
    '{@variantrule Cover|XPHB|Total Cover}',
    '{@variantrule Critical Hit|XPHB}',
    '{@variantrule Cube [Area of Effect]|XPHB|Cube}',
    '{@variantrule Curses|XPHB|Curse}',
    '{@variantrule Cylinder [Area of Effect]|XPHB|Cylinder}',
    '{@variantrule D20 Test|XPHB}',
    '{@variantrule D20 Test|XPHB|D20 Tests}',
    '{@variantrule Darkness|XPHB}',
    '{@variantrule Difficult Terrain|XPHB}',
    '{@variantrule Dim Light|XPHB}',
    '{@variantrule Disadvantage|XPHB}',
    '{@variantrule Emanation [Area of Effect]|XPHB|Emanation}',
    '{@variantrule Fly Speed|XPHB}',
    '{@variantrule Heavily Obscured|XPHB}',
    '{@variantrule High Jump|XPHB}',
    '{@variantrule Hit Points|XPHB}',
    '{@variantrule Hit Points|XPHB|Hit Point}',
    '{@variantrule Immunity|XPHB}',
    '{@variantrule Initiative|XPHB}',
    '{@variantrule Line [Area of Effect]|XPHB|Line}',
    '{@variantrule Long Jump|XPHB}',
    '{@variantrule Long Rest|XPHB}',
    '{@variantrule Object|XPHB}',
    '{@variantrule Possession|XPHB}',
    '{@variantrule Reaction|XPHB}',
    '{@variantrule Resistance|XPHB}',
    '{@variantrule Short Rest|XPHB|Short}',
    '{@variantrule Speed|XPHB}',
    '{@variantrule Sphere [Area of Effect]|XPHB|Sphere}',
    '{@variantrule Stable|XPHB}',
    '{@variantrule Swim Speed|XPHB}',
    '{@variantrule Temporary Hit Points|XPHB}',
    '{@variantrule Vulnerability|XPHB}',
];

export const spellUniqueFields = [
    'name',
    'source',
    'page',
    'level',
    'school',
    'time',
    'range',
    'components',
    'duration',
    'entries',
    'entriesHigherLevel',
    'miscTags',
    'hasFluffImages',
    'conditionInflict',
    'savingThrow',
    'affectsCreatureType',
    'areaTags',
    'damageInflict',
    'spellAttack',
    'otherSources',
    'abilityCheck',
    'scalingLevelDice',
    'meta',
    'reprintedAs',
    'srd',
    'basicRules',
    'damageResist',
    'alias',
    'conditionImmune',
    'damageVulnerable',
    'damageImmune',
    'hasFluff',
    'additionalSources',
    'srd52',
    'basicRules2024'
];
